package com.lkacz.pola

object Prefs {
    const val NAME = "ProtocolPrefs"
    const val KEY_PROTOCOL_URI = "PROTOCOL_URI"
    const val KEY_CURRENT_MODE = "CURRENT_MODE"
    const val KEY_CURRENT_PROTOCOL_NAME = "CURRENT_PROTOCOL_NAME"
    const val KEY_DEVELOPER_MODE = "DEVELOPER_MODE"
    const val KEY_PROTOCOL_PROGRESS_INDEX = "PROTOCOL_PROGRESS_INDEX"
    const val KEY_PROTOCOL_IN_PROGRESS = "PROTOCOL_IN_PROGRESS"
    const val KEY_PARTICIPANT_ID = "PARTICIPANT_ID"
    const val KEY_OUTPUT_FOLDER_URI = "OUTPUT_FOLDER_URI"
}
