name: CI

on:
  pull_request:
    branches: [ main, dev16 ]
  push:
    branches: [ main, dev16 ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Kotlin/Gradle Version Info
        run: ./gradlew --version

      - name: Assemble Debug
        run: ./gradlew assembleDebug --stacktrace --no-daemon

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest --stacktrace --no-daemon

      - name: ktlint Check
        run: ./gradlew ktlintCheck --stacktrace --no-daemon

      - name: Coverage Report
        run: ./gradlew jacocoTestReport --stacktrace --no-daemon

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: app/build/reports/jacoco/jacocoTestReport/html
          if-no-files-found: ignore

      - name: Dependency Updates (report only)
        run: ./gradlew dependencyUpdates --no-daemon || true

      - name: Upload dependency report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dependency-updates-report
          path: build/dependencyUpdates/report.txt
          if-no-files-found: ignore

      - name: Upload test reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-report
          path: app/build/reports/tests/testDebugUnitTest
          if-no-files-found: ignore
